### ISSUE TITLE
Potential confusion with Orbit.js

### ISSUE THREAD

**Issue by dgeb** [hugeinc/orbit#61]
Hello, I'm the creator of [Orbit.js](https://github.com/orbitjs/orbit.js), which predates your project by a couple years. I'm concerned about potential confusion between our projects, since they exist in a similar space. I noticed your project because, although we've just been publishing to bower to date, we'll be publishing the next version of orbit to npm (probably as "orbit.js" - I see you're using "orbitjs"). We'll also be launching orbitjs.com soon. Anyway, I wanted to raise your awareness about Orbit.js and ask you to consider renaming your work while it's still new. Thanks for your consideration!

**Comment by caiovaccaro** [comment]
Hi @dgeb ! How are you?

Honestly speaking, I'm not personally worried about the name. So I can definitely check internally what is the best approach here.

I did a small research and I remember finding other occurrences but somehow was not aware of your project and its relevance.

I will get back asap, thanks for reaching out!

**Comment by dgeb** [comment]
Thanks so much for following up, @caiovaccaro! 

I'm not usually concerned enough over OSS project naming to raise such an issue. However, it seems quite likely that developers might want to use our projects together in a javascript app: (my) orbit for managing data + state, and (your) orbit for managing business logic. I imagine most will avoid doing so based on the name overlap alone.

Well, thanks again for looking into this further and discussing it internally. Much appreciated!

**Comment by dgeb** [comment]
@caiovaccaro I love the new name! Thanks so much for making a change. I hope many projects will use Orbit.js and Lunar.js together :beers:

**Comment by caiovaccaro** [comment]
Yeah, me too! It was a nice way to meet anyway :)

See you around.
